[general]
filetype = "pdf"
output = "book"
sources = "*.md"

[pandoc.flags]
split-level = 2
epub-title-page = true
pdf-engine = "typst"
template = "./assets/templates/template"
lua-filter = "./assets/filters.lua"

[book]
title = "Title"
subtitle = "Subtitle"
lang = "en-US"
date = 2024
css = "assets/styles.css"
cover-image = "assets/cover.png"
author = "Maycon F. Melo"